
apiVersion: v1
kind: Service
metadata:
  name: go-random-quotes
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: go-random-quotes
  type: LoadBalancer
